Nama_panjang = input ("Siapa nama kamu? =")
Panggilan = input ("Dipanggil siapa? =")
Nim = (input("NIM kamu berapa ? ="))
Alamat = input("Dimana kamu tinggal? =")
Deskripsi_desa = input("Bisa deskripsikan kampung halamanmu? =")
Harapan_TI = input ("Harapan kamu sebagai lulusan TI nantinya? =")

print ("Nama Lengkap =", Nama_panjang)
print ("Nama Panggilan =", Panggilan)
print ("NIM =", Nim)
print ("Alamat Rumah =", Alamat)
print ("Deskripsi Tempat Tinggal =", Deskripsi_desa)
print ("Harapan di Teknik Industri =", Harapan_TI)

print ("Nama Lengkap = Fatihah Asy Syifa")
print ("NIM = I0322043")
print ("Tempat Tinggal = Bugel,Polokarto,Sukoharjo")
print ("Deskripsi Tempat Tinggal = Kabupaten Sukoharjo, dikenal dengan slogan makmurnya")
print ("Harapan di Teknik Industri = Mampu menciptakan gebrakan baru di industri 5.0")
print ("halooo")
print ("apa kabarrr")